# SELF-HEAL: Removed unused os import
# SELF-HEAL: Changed absolute import to relative import for package compatibility
from .base_linter import BaseDocumentLinter, ValidationReport


class ArchiLinter(BaseDocumentLinter):
    """
    Linter déterministe pour les documents d'Architecture.
    Étend la validation structurelle de base avec des règles métiers spécifiques.
    """
    
    # Mots-clés déterministes pour valider le détail des composants
    COMPONENT_KEYWORDS = ["responsabilité", "technologie", "responsable", "stack", "framework"]
    FLUX_KEYWORDS = ["flux", "données", "api", "message", "synchron", "asynchron", "événement"]
    ADR_KEYWORDS = ["décision", "adr", "choix", "alternative", "conséquence"]
    
    def validate_structure(self, target_doc_path: str) -> ValidationReport:
        # Sécurité : forcer l'extension .docx uniquement
        # SELF-HEAL: Cast to str to safely handle Path objects passed from __init__.py
        if not str(target_doc_path).lower().endswith(".docx"):
            return ValidationReport(
                is_valid=False,
                errors=["Format de fichier non supporté. Seuls les documents .docx sont autorisés."]
            )
            
        # 1. Validation de base (règles du template, sections obligatoires, mots minimum)
        base_report = super().validate_structure(target_doc_path)
        all_errors = list(base_report.errors)
        
        # 2. Extraction des sections pour vérifications métier
        sections = self.extract_sections(target_doc_path)
        
        # Vérification spécifique : Composants
        composants_paragraphs = sections.get("Composants", [])
        if composants_paragraphs:
            composants_text = " ".join(p.text for p in composants_paragraphs).lower()
            matched_keywords = [kw for kw in self.COMPONENT_KEYWORDS if kw in composants_text]
            
            # Score déterministe : au moins 2 mots-clés pertinents attendus
            if len(matched_keywords) < 2:
                all_errors.append(
                    f"Section 'Composants' incomplète. "
                    f"Attendez des détails sur la responsabilité et la technologie. "
                    f"Mot(s) détecté(s): {matched_keywords}"
                )
        elif "Composants" not in sections:
            if not any("Composants" in err for err in all_errors):
                all_errors.append("Section 'Composants' manquante.")
                
        # Vérification spécifique : Flux de données
        flux_paragraphs = sections.get("Flux de données", [])
        if flux_paragraphs:
            flux_text = " ".join(p.text for p in flux_paragraphs).lower()
            if not any(kw in flux_text for kw in self.FLUX_KEYWORDS):
                all_errors.append(
                    "Section 'Flux de données' ne contient pas de descripteurs de flux ou d'échanges."
                )
                
        # SELF-HEAL: Updated section key to match exact heading generated by template script
        adr_paragraphs = sections.get("Décisions techniques (ADR)", [])
        if adr_paragraphs:
            adr_text = " ".join(p.text for p in adr_paragraphs).lower()
            if not any(kw in adr_text for kw in self.ADR_KEYWORDS):
                all_errors.append(
                    "Section 'Décisions techniques' présente mais ne suit pas le format ADR attendu."
                )
                
        is_valid = len(all_errors) == 0 and base_report.is_valid
        return ValidationReport(
            is_valid=is_valid,
            errors=all_errors,
            warnings=list(base_report.warnings),
            details=dict(base_report.details)
        )
